### ISSUE TITLE
Problem with exports

### ISSUE THREAD

**Issue by agustinmulet** [wobsoriano/vue-zustand#1]
Hi! I've noticed that the `exports` part in the package.json is different than the files generated on build.

This is the package.json:

```
  "exports": {
    "require": "./dist/index.js",
    "import": "./dist/index.mjs"
  },
```

But the files generated are `.js` and `.cjs`. Reading the documentation on `tsup` (the tool used on the build-fast script) it states that that happens if the type is set to `module` on package.json https://tsup.egoist.sh/#bundle-formats

Maybe it's better to change the type of the package? Or change the filenames on the exports on the package.json?

Thanks for your hard work!

**Comment by wobsoriano** [comment]
Thanks for this!

https://github.com/wobsoriano/vue-zustand/commit/d99b7efc21f3a96b8bcdef18dc6836d514e65be2
