### ISSUE TITLE
Would this library work with vue 2.7.X?

### ISSUE THREAD

**Issue by lgn-lvx3** [wobsoriano/vue-zustand#6]
I'm trying to use Zustand to share state management between React/Vue but I'm bound to 2.7. I see that vue3 is used in the deps, would this work with vue 2.7 as well?

**Comment by Zikoat** [comment]
@lgn-lvx3 I have successfully used zustand with vue 2.6/2.7 without this library. 

See this gist: https://gist.github.com/Zikoat/ec47ff3646f889d09f8c6d350e6060f6

I haven't created a library for this yet, but the code is only 10 lines, so it isn't too much to copy. I also have not seen any bugs using this approach yet. 

@wobsoriano Could i add the gist to the readme for any users who want to use it with vue 2?

**Comment by lgn-lvx3** [comment]
Hell yeah @Zikoat ill try it out!
Thanks 👍
